version: "2"

run:
  timeout: 5m
  tests: true
  go: "1.25"

linters:
  enable:
    - errcheck
    - govet
    - staticcheck
    - unused
    - ineffassign
    - misspell
    - unconvert
  settings:
    misspell:
      locale: US

issues:
  max-issues-per-linter: 0
  max-same-issues: 0
