---
version: 2
project_name: fyaml

builds:
  - id: fyaml
    main: ./cmd/fyaml
    binary: fyaml
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
    env:
      - CGO_ENABLED=0
    flags:
      - -trimpath
    ldflags:
      - -s -w
      - -X github.com/jksmth/fyaml/internal/version.Version={{.Version}}
      - -X github.com/jksmth/fyaml/internal/version.Commit={{.Commit}}
      - -X github.com/jksmth/fyaml/internal/version.Date={{.Date}}

archives:
  - id: default
    formats:
      - tar.gz
    format_overrides:
      - goos: windows
        formats:
          - zip
    files:
      - LICENSE
      - README.md
      - NOTICE

checksum:
  name_template: "checksums.txt"

signs:
  - id: checksum
    cmd: cosign
    signature: "${artifact}.sigstore.json"
    args:
      - sign-blob
      - "--bundle=${signature}"
      - "--yes"
      - "${artifact}"
    artifacts: checksum
    env:
      - COSIGN_EXPERIMENTAL=1
  - id: archive
    cmd: cosign
    signature: "${artifact}.sigstore.json"
    args:
      - sign-blob
      - "--bundle=${signature}"
      - "--yes"
      - "${artifact}"
    artifacts: archive
    env:
      - COSIGN_EXPERIMENTAL=1

sboms:
  - artifacts: archive
    documents:
      - "${artifact}.sbom.spdx.json"
    cmd: syft
    args:
      - "$artifact"
      - "--output"
      - "spdx-json=$document"

dockers_v2:
  - images:
      - "ghcr.io/jksmth/fyaml"
    tags:
      - "{{ .Version }}"
      - latest
    platforms:
      - linux/amd64
      - linux/arm64
    sbom: true

docker_signs:
  - cmd: cosign
    artifacts: images
    args:
      - sign
      - "--yes"
      - "${artifact}"

release:
  mode: keep-existing
