---
version: 2
project_name: fyaml

builds:
  - id: fyaml
    main: .
    binary: fyaml
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
    env:
      - CGO_ENABLED=0
    flags:
      - -trimpath
    ldflags:
      - -s -w
      - -X github.com/jksmth/fyaml/internal/version.Version={{.Version}}
      - -X github.com/jksmth/fyaml/internal/version.Commit={{.Commit}}
      - -X github.com/jksmth/fyaml/internal/version.Date={{.Date}}

archives:
  - id: default
    formats:
      - tar.gz
    format_overrides:
      - goos: windows
        formats:
          - zip
    files:
      - LICENSE
      - README.md
      - NOTICE

checksum:
  name_template: 'checksums.txt'

signs:
  - id: checksum
    cmd: cosign
    signature: "${artifact}.sigstore"
    args:
      - sign-blob
      - "--bundle=${signature}"
      - "--yes"
      - "${artifact}"
    artifacts: checksum
    env:
      - COSIGN_EXPERIMENTAL=1
  - id: archive
    cmd: cosign
    signature: "${artifact}.sigstore"
    args:
      - sign-blob
      - "--bundle=${signature}"
      - "--yes"
      - "${artifact}"
    artifacts: archive
    env:
      - COSIGN_EXPERIMENTAL=1

sboms:
  - artifacts: archive
    documents:
      - "${artifact}.sbom.spdx.json"
    cmd: syft
    args:
      - "$artifact"
      - "--output"
      - "spdx-json=$document"

release:
  disable: true

