FROM alpine:3.24@sha256:28bd5fe8b56d1bd048e5babf5b10710ebe0bae67db86916198a6eec434943f8b

ARG TARGETPLATFORM

# Create non-root user
RUN addgroup -S fyaml && adduser -S fyaml -G fyaml

COPY --chown=fyaml:fyaml $TARGETPLATFORM/fyaml /usr/local/bin/fyaml

USER fyaml

ENTRYPOINT ["/usr/local/bin/fyaml"]
