FROM alpine:3.23@sha256:865b95f46d98cf867a156fe4a135ad3fe50d2056aa3f25ed31662dff6da4eb62

ARG TARGETPLATFORM

# Create non-root user
RUN addgroup -S fyaml && adduser -S fyaml -G fyaml

COPY --chown=fyaml:fyaml $TARGETPLATFORM/fyaml /usr/local/bin/fyaml

USER fyaml

ENTRYPOINT ["/usr/local/bin/fyaml"]
