FROM alpine:3.23@sha256:5b10f432ef3da1b8d4c7eb6c487f2f5a8f096bc91145e68878dd4a5019afde11

ARG TARGETPLATFORM

# Create non-root user
RUN addgroup -S fyaml && adduser -S fyaml -G fyaml

COPY --chown=fyaml:fyaml $TARGETPLATFORM/fyaml /usr/local/bin/fyaml

USER fyaml

ENTRYPOINT ["/usr/local/bin/fyaml"]
